#!/usr/bin/env python3
"""
Imports Tabler Icons (MIT, https://github.com/tabler/tabler-icons) outline SVGs
as Android VectorDrawables. Stdlib only.

    python tools/icons/import_tabler.py --self-test   # converter unit test, no network
    python tools/icons/import_tabler.py --check       # verify every chosen name exists in the release
    python tools/icons/import_tabler.py               # download (cached), convert, write drawables

Item icons:  app/src/main/res-packs/drawable/<group>_<name>_itemicon.xml
             (picked up by DrawableResItemIconRepository, group = text before the first "_")
UI icons:    app/src/main/res/drawable/ic_tabler_<name>.xml
Re-running removes previously generated files (they carry GENERATED_MARKER) first,
the original icon packs are never touched.
"""

import argparse
import io
import re
import sys
import tarfile
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path
from xml.sax.saxutils import quoteattr

TABLER_VERSION = "3.31.0"
TARBALL_URL = f"https://registry.npmjs.org/@tabler/icons/-/icons-{TABLER_VERSION}.tgz"
STROKE_WIDTH = "1.75"

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[1]
CACHE_DIR = HERE / ".cache"
ITEM_ICONS_DIR = REPO_ROOT / "app" / "src" / "main" / "res-packs" / "drawable"
UI_ICONS_DIR = REPO_ROOT / "app" / "src" / "main" / "res" / "drawable"
LICENSE_OUT = HERE / "LICENSE-tabler-icons.txt"
NAMES_OUT = HERE / "generated_item_icon_names.txt"
GENERATED_MARKER = "Generated by tools/icons/import_tabler.py"

EXISTING_PACK_GROUPS = {"finances", "food", "hobbies", "other", "services", "socializing", "transport"}

# group -> Tabler outline icon names. Edit freely, then re-run the script.
ITEM_ICON_GROUPS = {
    "meal": [
        "shopping-cart", "basket", "apple", "carrot", "bread", "cheese", "egg", "fish", "meat",
        "milk", "pizza", "burger", "salad", "soup", "coffee", "cup", "beer", "bottle",
        "glass-full", "tools-kitchen-2", "chef-hat", "ice-cream", "cookie", "candy", "cake",
        "paper-bag",
    ],
    "vehicle": [
        "car", "bus", "train", "plane", "car-suv", "motorbike", "scooter", "scooter-electric", "bike",
        "gas-station", "charging-pile", "parking", "steering-wheel", "car-garage", "road", "ship",
    ],
    "travel": ["luggage", "map-pin", "beach", "tent", "world", "mountain"],
    "home": [
        "home", "building", "sofa", "bed", "armchair", "lamp", "bulb", "plug", "bolt", "droplet",
        "flame", "wifi", "router", "key", "tool", "hammer", "paint", "wash-machine", "fridge",
        "plant", "trash", "truck-delivery", "door",
    ],
    "health": [
        "heart", "heartbeat", "first-aid-kit", "pill", "vaccine", "stethoscope", "dental", "eye",
        "barbell", "run", "yoga", "swimming",
    ],
    "care": ["scissors", "razor", "bath", "massage"],
    "shop": [
        "shopping-bag", "shirt", "shoe", "hanger", "eyeglass", "diamond", "gift", "device-mobile",
        "device-laptop", "device-desktop", "device-tv", "headphones", "camera", "device-watch",
        "tag", "discount", "building-store", "package",
    ],
    "digital": [
        "brand-youtube", "brand-spotify", "brand-netflix", "brand-aws", "brand-azure",
        "brand-google", "brand-apple", "brand-steam", "brand-amazon", "brand-github",
        "brand-openai", "brand-telegram", "cloud", "server", "world-www",
    ],
    "leisure": [
        "device-gamepad-2", "movie", "ticket", "music", "microphone", "book", "palette",
        "ball-football", "ball-basketball", "puzzle", "dice", "confetti", "balloon", "cards",
        "chess", "masks-theater", "smoking",
    ],
    "money": [
        "cash", "coin", "coins", "credit-card", "wallet", "pig-money", "building-bank", "receipt",
        "receipt-tax", "receipt-refund", "report-money", "chart-line", "currency-bitcoin",
        "currency-dollar", "currency-euro", "moneybag", "cash-banknote", "arrows-exchange",
        "percentage", "scale",
    ],
    "people": [
        "baby-carriage", "paw", "dog", "cat", "user", "users", "friends", "heart-handshake",
        "school", "backpack",
    ],
    "work": ["briefcase", "building-factory", "presentation", "plane-departure", "id-badge"],
    "misc": [
        "dots", "question-mark", "star", "flag", "bell", "calendar", "clock", "lock", "shield",
        "umbrella", "recycle", "phone", "mail", "box", "sun", "leaf",
    ],
}

UI_ICONS = [
    "wallet", "chart-donut", "list-details", "chart-bar", "user-circle", "chevron-left",
    "chevron-right", "calendar", "backspace", "pencil", "trash", "check", "arrows-exchange",
    # Redesign: controls, action sheets, settings, inbox, rules.
    "plus", "minus", "x", "arrow-left", "chevron-down", "chevron-up", "settings", "adjustments-horizontal",
    "layout-grid", "arrow-down-left", "arrow-up-right", "scale", "arrow-back-up", "inbox", "archive",
    "eye", "eye-off", "circle", "circle-check", "sun", "moon", "device-mobile", "palette", "lock",
    "bell", "logout", "copy", "info-circle", "filter", "clock", "notes", "help-circle", "cards",
    "credit-card", "pig-money", "currency-euro", "fingerprint", "alert-triangle", "search",
    "divide", "math-function", "equal", "receipt", "message-question", "grip-vertical", "id",
    "cloud-upload", "arrows-left-right", "dots", "chart-pie", "category", "tag",
    "bolt", "shield-check", "apps",
]

SVG_NS = "{http://www.w3.org/2000/svg}"
RES_NAME = re.compile(r"^[a-z][a-z0-9_]*$")


def fmt(x: float) -> str:
    s = f"{x:.3f}".rstrip("0").rstrip(".")
    return "0" if s in ("", "-0") else s


def num(attrs: dict, key: str) -> float:
    return float(attrs.get(key, "0") or "0")


def element_to_path_data(tag: str, a: dict) -> str:
    if tag == "path":
        return a["d"]
    if tag == "circle":
        cx, cy, r = num(a, "cx"), num(a, "cy"), num(a, "r")
        return (f"M{fmt(cx - r)},{fmt(cy)}"
                f"a{fmt(r)},{fmt(r)} 0 1,0 {fmt(2 * r)},0"
                f"a{fmt(r)},{fmt(r)} 0 1,0 {fmt(-2 * r)},0")
    if tag == "ellipse":
        cx, cy, rx, ry = num(a, "cx"), num(a, "cy"), num(a, "rx"), num(a, "ry")
        return (f"M{fmt(cx - rx)},{fmt(cy)}"
                f"a{fmt(rx)},{fmt(ry)} 0 1,0 {fmt(2 * rx)},0"
                f"a{fmt(rx)},{fmt(ry)} 0 1,0 {fmt(-2 * rx)},0")
    if tag == "line":
        return f"M{fmt(num(a, 'x1'))},{fmt(num(a, 'y1'))}L{fmt(num(a, 'x2'))},{fmt(num(a, 'y2'))}"
    if tag in ("polyline", "polygon"):
        values = [float(v) for v in re.split(r"[\s,]+", a["points"].strip()) if v]
        pairs = [f"{fmt(values[i])},{fmt(values[i + 1])}" for i in range(0, len(values) - 1, 2)]
        return "M" + "L".join(pairs) + ("Z" if tag == "polygon" else "")
    if tag == "rect":
        x, y, w, h = num(a, "x"), num(a, "y"), num(a, "width"), num(a, "height")
        rx = num(a, "rx") if "rx" in a else num(a, "ry")
        ry = num(a, "ry") if "ry" in a else rx
        rx, ry = min(rx, w / 2), min(ry, h / 2)
        if rx == 0 and ry == 0:
            return f"M{fmt(x)},{fmt(y)}h{fmt(w)}v{fmt(h)}h{fmt(-w)}Z"
        return (f"M{fmt(x + rx)},{fmt(y)}h{fmt(w - 2 * rx)}"
                f"a{fmt(rx)},{fmt(ry)} 0 0,1 {fmt(rx)},{fmt(ry)}v{fmt(h - 2 * ry)}"
                f"a{fmt(rx)},{fmt(ry)} 0 0,1 {fmt(-rx)},{fmt(ry)}h{fmt(-(w - 2 * rx))}"
                f"a{fmt(rx)},{fmt(ry)} 0 0,1 {fmt(-rx)},{fmt(-ry)}v{fmt(-(h - 2 * ry))}"
                f"a{fmt(rx)},{fmt(ry)} 0 0,1 {fmt(rx)},{fmt(-ry)}Z")
    raise ValueError(f"Unsupported SVG element <{tag}>")


def svg_to_vector_drawable(svg_text: str, comment: str) -> str:
    root = ET.fromstring(svg_text)
    root_stroke = root.attrib.get("stroke", "currentColor")
    path_xml = []
    for el in root.iter():
        tag = el.tag.replace(SVG_NS, "")
        if tag in ("svg", "title", "desc", "defs"):
            continue
        if tag == "g":
            if "transform" in el.attrib:
                raise ValueError("<g transform> is not supported")
            continue
        stroke = el.attrib.get("stroke", root_stroke)
        fill = el.attrib.get("fill", "none")
        is_stroked = stroke != "none"
        is_filled = fill != "none"
        if not is_stroked and not is_filled:
            # Tabler's invisible 24x24 bounding box.
            continue
        attrs = [f"android:pathData={quoteattr(element_to_path_data(tag, el.attrib))}",
                 f'android:fillColor="{"#FF000000" if is_filled else "#00000000"}"']
        if is_stroked:
            attrs += ['android:strokeColor="#FF000000"',
                      f'android:strokeWidth="{STROKE_WIDTH}"',
                      'android:strokeLineCap="round"',
                      'android:strokeLineJoin="round"']
        path_xml.append("    <path\n        " + "\n        ".join(attrs) + " />")
    if not path_xml:
        raise ValueError("No drawable elements")
    return ("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
            f"<!-- {GENERATED_MARKER}. {comment} -->\n"
            "<vector xmlns:android=\"http://schemas.android.com/apk/res/android\"\n"
            "    android:width=\"24dp\"\n"
            "    android:height=\"24dp\"\n"
            "    android:viewportWidth=\"24\"\n"
            "    android:viewportHeight=\"24\">\n"
            + "\n".join(path_xml) + "\n</vector>\n")


def self_test() -> None:
    svg = ('<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" '
           'fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">'
           '<path stroke="none" d="M0 0h24v24H0z" fill="none"/>'
           '<path d="M3 12h18" /><circle cx="12" cy="12" r="2" /><line x1="1" y1="2" x2="3" y2="4" />'
           '<rect x="2" y="3" width="10" height="6" rx="1" /><polyline points="1 1 2 2 3 1" />'
           '<path d="M5 5h.01" fill="currentColor" stroke="none" /></svg>')
    out = svg_to_vector_drawable(svg, "test")
    assert out.count("<path") == 6, out
    assert 'android:pathData="M3 12h18"' in out, out
    assert 'android:pathData="M10,12a2,2 0 1,0 4,0a2,2 0 1,0 -4,0"' in out, out
    assert 'android:pathData="M1,2L3,4"' in out, out
    assert 'android:pathData="M3,3h8a1,1 0 0,1 1,1v4a1,1 0 0,1 -1,1h-8a1,1 0 0,1 -1,-1v-4a1,1 0 0,1 1,-1Z"' in out, out
    assert 'android:pathData="M1,1L2,2L3,1"' in out, out
    assert out.count('android:fillColor="#FF000000"') == 1, out
    assert out.count('android:strokeColor="#FF000000"') == 5, out
    assert 'M0 0h24v24H0z' not in out, out
    ET.fromstring(out.split("\n", 2)[2])  # well-formed without the prolog/comment
    print("self-test OK")


def res_name(group: str, icon: str) -> str:
    name = f"{group}_{icon.replace('-', '_')}"
    if not RES_NAME.match(name):
        raise ValueError(f"Invalid resource name {name}")
    return name


def load_tarball() -> tarfile.TarFile:
    CACHE_DIR.mkdir(exist_ok=True)
    cached = CACHE_DIR / f"tabler-icons-{TABLER_VERSION}.tgz"
    if not cached.exists():
        print(f"Downloading {TARBALL_URL}")
        with urllib.request.urlopen(TARBALL_URL) as response:
            cached.write_bytes(response.read())
    return tarfile.open(fileobj=io.BytesIO(cached.read_bytes()), mode="r:gz")


def outline_svgs(tar: tarfile.TarFile) -> dict:
    result = {}
    for member in tar.getmembers():
        match = re.search(r"/icons/outline/([a-z0-9-]+)\.svg$", member.name)
        if match:
            result[match.group(1)] = member
    if not result:
        raise SystemExit("No icons/outline/*.svg in the tarball; the package layout changed")
    return result


def remove_generated(directory: Path, pattern: str) -> int:
    removed = 0
    for path in directory.glob(pattern):
        if GENERATED_MARKER in path.read_text(encoding="utf-8", errors="ignore"):
            path.unlink()
            removed += 1
    return removed


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()

    if args.self_test:
        self_test()
        return

    clashing = EXISTING_PACK_GROUPS & ITEM_ICON_GROUPS.keys()
    if clashing:
        raise SystemExit(f"Groups clash with existing packs: {clashing}")

    tar = load_tarball()
    svgs = outline_svgs(tar)
    wanted = {icon for icons in ITEM_ICON_GROUPS.values() for icon in icons} | set(UI_ICONS)
    missing = sorted(wanted - svgs.keys())
    if missing:
        raise SystemExit("Not in Tabler " + TABLER_VERSION + ", pick similar names at "
                         "https://tabler.io/icons: " + ", ".join(missing))
    if args.check:
        print(f"All {len(wanted)} icons exist in Tabler {TABLER_VERSION}")
        return

    removed = remove_generated(ITEM_ICONS_DIR, "*_itemicon.xml") + remove_generated(UI_ICONS_DIR, "ic_tabler_*.xml")

    def read_svg(icon: str) -> str:
        return tar.extractfile(svgs[icon]).read().decode("utf-8")

    item_names = []
    for group, icons in ITEM_ICON_GROUPS.items():
        for icon in icons:
            name = res_name(group, icon)
            comment = f'Tabler Icons {TABLER_VERSION} "{icon}", MIT, see tools/icons/LICENSE-tabler-icons.txt'
            (ITEM_ICONS_DIR / f"{name}_itemicon.xml").write_text(
                svg_to_vector_drawable(read_svg(icon), comment), encoding="utf-8")
            item_names.append(name)
    for icon in UI_ICONS:
        name = "ic_tabler_" + icon.replace("-", "_")
        comment = f'Tabler Icons {TABLER_VERSION} "{icon}", MIT, see tools/icons/LICENSE-tabler-icons.txt'
        (UI_ICONS_DIR / f"{name}.xml").write_text(
            svg_to_vector_drawable(read_svg(icon), comment), encoding="utf-8")

    license_member = next(m for m in tar.getmembers() if m.name.endswith("/LICENSE"))
    LICENSE_OUT.write_bytes(tar.extractfile(license_member).read())
    NAMES_OUT.write_text("\n".join(item_names) + "\n", encoding="utf-8")
    print(f"Removed {removed} old files, wrote {len(item_names)} item icons and {len(UI_ICONS)} UI icons")


if __name__ == "__main__":
    sys.exit(main())
